Print generated files as string instead []byte
NethermindEth/sedge pull request #121
Opened 2022-09-27 13:23 UTC by stdevMac

Resolves #120

## Changes:
- Cast read file to string and print it as string instead of []byte

## Types of changes
- [x] Bugfix (non-breaking change which fixes an issue)

## Testing
**Requires testing**
2- [x] No

2022-09-27 19:15 UTC, AntiD2ta approved these changes

2022-09-27 19:15 UTC, AntiD2ta requested changes
Good catch. Please update the CHANGELOG with this fix

2022-09-27 19:20 UTC, cbermudez97 approved these changes

2022-10-04 20:17 UTC, AntiD2ta approved these changes

2022-10-04 20:21 UTC, merged