Add Erigon Execution wxxxxxxx
NethermindEth/sedge pull request #156
Opened 2022-11-03 16:34 UTC by stdevMac

E## Changes:
- Add erigon Execution client to stack

## Types of changes

What types of changes does your code introduce?
- [x] New feature (non-breaking change which adds functionality)

## Testing
- [x] Yes
**In case you checked yes, did you write tests?**

- [ ] Yes
- [x] No

**Comments about testing , should you have some** (optional)
Run smoke tests

2022-11-06 03:20 UTC, AntiD2ta requested changes
Update /scripts/check-image-updates.sh with Erigon, so we can get the latest release from Erigon as soon as possible.

2022-11-06 03:20 UTC, AntiD2ta commented on templates/services/merge/execution/erigon.tmpl
> +    - --chain={{if .SplittedNetwork}}${EL_NETWORK}{{else}}${NETWORK}{{end}}
```suggestion
    - --txpool.disable
    - --chain={{if .SplittedNetwork}}${EL_NETWORK}{{else}}${NETWORK}{{end}}
```

2022-11-06 03:20 UTC, AntiD2ta commented on templates/services/merge/execution/erigon.tmpl
> +  execution:
```suggestion
{{ define "execution" }}
  execution:
```

2022-11-07 15:11 UTC, stdevMac commented
@AntiD2ta just solved what you requested, please review it again!

2022-12-03 14:45 UTC, AntiD2ta approved these changes

2022-12-03 14:45 UTC, merged