Add documentation for supported networks and Clients
NethermindEth/sedge pull request #173
Opened 2022-11-21 23:36 UTC by stdevMac

## Changes:
- Added documentation for supported networks and clients on each of those networks

## Types of changes
- [x] Documentation Update

## Testing
**Requires testing**

- [ ] Yes
- [x] No

**In case you checked yes, did you write tests?**

- [ ] Yes
- [x] No

2022-11-28 21:02 UTC, AntiD2ta requested changes
Changes requested. Good idea. If Besu and Erigon PRs are merged before this, then they must be added to the proper sections in the new pages.

2022-12-05 19:50 UTC, stdevMac commented on docs/docs/networks/goerli.mdx
> +## Supported Consensus Clients
done

2022-12-05 19:50 UTC, stdevMac commented on docs/docs/networks/sepolia.mdx
> +Sepolia is a proof-of-work (PoW) testnet where dApp developers can test their applications. What differentiates Sepolia
done

2022-12-05 19:51 UTC, stdevMac commented on docs/docs/networks/mainnet.mdx
> +Sedge uses Mainnet as default network, so you don't have to specify.
done

2022-12-05 19:51 UTC, stdevMac commented on docs/docs/networks/mainnet.mdx
> +earn staking rewards and is the network that all users interact with to send transactions and store state. Mainnet is
done

2022-12-05 19:51 UTC, stdevMac commented on docs/docs/networks/goerli.mdx
> +sedge cli --no-mev-boost=true
done

2022-12-05 19:51 UTC, stdevMac commented on docs/docs/networks/goerli.mdx
> +We support [mev-boost](https://github.com/flashbots/mev-boost) on mainnet by default, in case you want to remove it,
done

2022-12-05 19:51 UTC, stdevMac commented on docs/docs/networks/goerli.mdx
> +main Ethereum network. The Proof-of-Authority test network was established in March 2019. It uses the Clique consensus
done

2022-12-05 19:51 UTC, stdevMac commented on docs/docs/networks/gnosis.mdx
> +It is a permissionless network that is governed by the Gnosis community.
done

2022-12-05 19:51 UTC, stdevMac commented on docs/docs/networks/chiado.mdx
> +decentralized prediction markets..
done

2022-12-22 23:43 UTC, AntiD2ta requested changes
Requested changes again. Check new comments

2022-12-22 23:43 UTC, AntiD2ta commented on docs/docs/networks/goerli.mdx
> +Proof-of-Stake following the network’s total block difficulty having crossed 10,079,000 on August 10.
```suggestion
Goerli is an Ethereum test network that allows for blockchain development testing before deployment on Mainnet, the
main Ethereum network. The test network was established in March 2019 with Proof-of-Authority. It uses the Clique consensus
mechanism and was originally proposed by Chainsafe and Afri Schoedon. Goerli has successfully transitioned to
Proof-of-Stake following the network’s total block difficulty having crossed 10,079,000 on August 10th, 2022.
```

2022-12-22 23:43 UTC, AntiD2ta commented on docs/docs/networks/goerli.mdx
> +## Supported Consensus Clients
Still wrong order

2022-12-22 23:43 UTC, AntiD2ta commented on docs/docs/networks/sepolia.mdx
> +applications will perform under the harshest conditions.
This is referring to the time Sepolia was PoW and you talking using present tense. Update this please and focus on Sepolia being a public network but with permissioned validator sets.

2023-01-03 16:07 UTC, stdevMac commented on docs/docs/networks/goerli.mdx
> +Proof-of-Stake following the network’s total block difficulty having crossed 10,079,000 on August 10.
Solved here [ffde355](https://github.com/NethermindEth/sedge/pull/173/commits/ffde355300b994a40dbc1d6fdae4ede7652ad890)

2023-01-03 16:08 UTC, stdevMac commented on docs/docs/networks/goerli.mdx
> +## Supported Consensus Clients
Solved here [ffde355](https://github.com/NethermindEth/sedge/pull/173/commits/ffde355300b994a40dbc1d6fdae4ede7652ad890)

2023-01-17 17:57 UTC, AntiD2ta requested changes
Three more minor changes to go

2023-01-17 17:57 UTC, AntiD2ta commented on CHANGELOG.md
> +- Documentation for all supported networks and clients on each of them.
```suggestion
- Documentation for all supported networks and clients.
```

2023-01-17 17:57 UTC, AntiD2ta commented on docs/docs/networks/goerli.mdx
> +main Ethereum network. The test network was established in March 2019 with Proof-of-Authority. It uses the Clique consensus
```suggestion
main Ethereum network. The test network was established in March 2019 with Proof-of-Authority. It used to use the Clique consensus
```

2023-01-17 17:57 UTC, AntiD2ta commented on docs/docs/networks/sepolia.mdx
> +It can process thousands of transactions per second and is capable of handling a large number of users.
```suggestion
Sepolia is a permissioned Ethereum test network. Along Goerli, it is one of the testnets that is maintained after The Merge. The initial version of Sepolia used a proof-of-work (PoW) consensus mechanism. However, in the light of The Merge, Sepolia followed the mainnet’s example and merged with the proof-of-stake (PoS) Sepolia Beacon Chain. So, Sepolia is now, just like Ethereum, a PoS chain. Furthermore, Sepolia is almost an identical copy of Ethereum, so it accurately mimics the mainnet and supports accurate testing. This enables developers to design, create, test, and track their project’s public performance before going live. 
```

2023-01-18 22:23 UTC, AntiD2ta approved these changes
Approved!

2023-01-18 22:32 UTC, merged