[Fix] AssignPorts test
NethermindEth/sedge pull request #184
Opened 2022-11-30 15:16 UTC by adriantpaez

Currently, the `AssignPorts` test behavior isn't consistent, and the main reason is the way _default ports_ map keys are traversed during a port assignation because Go doesn't traverse the keys in order. To avoid this keys are sorted now before processing them.

## Changes:
- Fix some typos
- Update the `AssignPorts` util function

## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)

## Testing
**Requires testing**

- [x] Yes

**In case you checked yes, did you write tests?**

- [x] No, because tests are already written

2022-11-30 15:31 UTC, stdevMac approved these changes

2022-12-03 14:25 UTC, AntiD2ta approved these changes

2022-12-03 14:27 UTC, AntiD2ta requested changes

2022-12-03 14:27 UTC, AntiD2ta commented on CHANGELOG.md
> +- Fix inconsistent behavior of `AssignPorts` function test
Please update this and put it under **Unreleased**. Great job, nice finding

2022-12-03 23:23 UTC, AntiD2ta approved these changes

2022-12-03 23:24 UTC, merged