Feature/set name to containers
NethermindEth/sedge pull request #220
Opened 2023-01-19 22:42 UTC by stdevMac

## Changes:
- Added flag `--container-tag` to add a suffix to sedge containers name.

## Types of changes
- [x] New feature (non-breaking change which adds functionality)

2023-01-20 03:09 UTC, AntiD2ta reviewed
Although this PR needs to be reviewed mostly by @adriantpaez. I have a main concern with the name convention you choose that is not the same as we agreed. Need that to be discussed before proceeding to review the entire PR

2023-01-23 16:00 UTC, stdevMac commented on internal/pkg/services/services.go
> +	ServiceCtValidatorImport    = "validator-import-client"
Was a mistake, already fixed it

2023-01-25 12:11 UTC, adriantpaez commented on internal/pkg/services/services.go
> +	ServiceCtValidatorImport    = "validator-import-client"
`ServiceCtSlashingData` still without the `sedge` prefix

2023-01-27 12:07 UTC, adriantpaez approved these changes

2023-02-19 20:26 UTC, AntiD2ta requested changes
Minor changes requested. Is almost there! Good work

2023-02-19 20:26 UTC, AntiD2ta commented on cli/actions/generation_test.go
> +	// Check that the execution container name is `sedge-execution-client_sampleTag'.
```suggestion
	// Check that the execution container name is `sedge-execution-client-sampleTag'.
```

2023-02-19 20:26 UTC, AntiD2ta commented on internal/pkg/generate/types.go
> +	ContainerTags           string
Change to `ContainerTag` please, is only one tag. Isn't it?

2023-02-19 20:26 UTC, AntiD2ta commented on cli/actions/generation_test.go
> +	// Check that the execution container name is `sedge-execution-client_sampleTag'.
If there isn't any tag you should test if the suffix `-sampleTag` is not there

2023-02-20 11:46 UTC, AntiD2ta approved these changes
Approved!

2023-02-20 11:46 UTC, merged