Add check for urls flags in generate command
NethermindEth/sedge pull request #252
Opened 2023-02-27 22:18 UTC by cbermudez97

## Changes:
- Add checks for urls flags in generate command
## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [x] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Other (please describe): 

## Testing
**Requires testing**

- [x] Yes
- [ ] No

**In case you checked yes, did you write tests?**

- [x] Yes
- [ ] No

2023-02-28 18:02 UTC, AntiD2ta approved these changes
Approved! Need another review

2023-03-01 14:56 UTC, adriantpaez requested changes

2023-03-01 14:56 UTC, adriantpaez commented on cli/sub_gen.go
> +	cmd.Flags().StringSliceVar(&flags.relayURLs, "relay-urls", []string{}, "List of comma separated relay URLs used to connect to mev relay. Example: 'sedge generate mevboost --relay-url=https://0xac6e7
Could this example be moved to the Example property of the mevboost [`cobra.Command`](https://pkg.go.dev/github.com/spf13/cobra#Command) instance?

2023-03-01 15:14 UTC, adriantpaez approved these changes

2023-03-01 15:23 UTC, merged