Add holesky network
NethermindEth/sedge pull request #320
Opened 2023-10-13 10:32 UTC by stdevMac

## Changes:
- Add holesky network

## Types of changes
- [x] New feature (non-breaking change which adds functionality)

## Testing
**Requires testing**

- [x] Yes

**In case you checked yes, did you write tests?**

- [x] Yes

2023-10-13 13:47 UTC, AntiD2ta requested changes

2023-10-13 13:47 UTC, AntiD2ta commented on CHANGELOG.md
> +- Integrate Holesky network.make
```suggestion
- Integrate Holesky network.
```

2023-10-13 13:47 UTC, AntiD2ta commented on configs/init.go
> +			"enr:-Le4QLoE1wFHSlGcm48a9ZESb_MRLqPPu6G0vHqu4MaUcQNDHS69tsy-zkN0K6pglyzX8m24mkb-LtBcbjAYdP1uxm4BhGV0aDKQabfZdAQBcAAAAQAAAAAAAIJpZIJ2NIJpcIQ5gR6Wg2lwNpAgAUHQBwEQAAAAAAAAADR-iXNlY3AyNTZrMaEDPMSNdcL
Remove bootnodes please

2023-10-16 08:23 UTC, stdevMac commented on CHANGELOG.md
> +- Integrate Holesky network.make
Fixed on c77c44f4b6d7ffd93eef5419935e1616cca0d066

2023-10-16 08:30 UTC, AntiD2ta approved these changes

2023-10-16 08:30 UTC, merged