Remove support for Goerli
NethermindEth/sedge pull request #372
Opened 2024-04-23 12:47 UTC by khalifaa55

Fixes | Closes | Resolves #

## Changes:
- Remove support for Goerli from Sedge
## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [x] Other (please describe): removing feature

## Testing
**Requires testing**

- [x] Yes
- [ ] No

**In case you checked yes, did you write tests?**

- [x] Yes
- [ ] No

**Comments about testing , should you have some** (optional)
adjusted `network_test.go` : `TestNetworkCheck` function

2024-05-13 04:31 UTC, stdevMac requested changes

2024-05-13 04:31 UTC, stdevMac commented on README.md
> +### Goerli (Unsupported)
Please remove this section, and everything that mentions Goerli in the readme and the docs. Unless is to say that it's unsupported

2024-05-13 04:31 UTC, stdevMac commented on cli/sub_gen.go
> +On mainnet, and sepolia mev-boost will be activated by default unless you run it with --no-mev-boost flag.
```suggestion
On mainnet and sepolia mev-boost will be activated by default unless you run it with --no-mev-boost flag.
```

2024-05-13 04:31 UTC, stdevMac commented on docs/docs/networks/goerli.mdx
> +# UNSUPPORTED
I think is better just to remove the file, since might be confusing for others if they don't read the `UNSOPPORTED`.

2024-05-16 11:21 UTC, adriantpaez requested changes
Some remaining details:
- Remove goerli from the import keys process [here](https://github.com/NethermindEth/sedge/blob/b4ff9dd1f60d1294fbf993749742bb9cfba40445/cli/actions/importKeys.go#L232) and from the associated tests
- Exclude Goerli from [this doc page](https://github.com/NethermindEth/sedge/blob/b4ff9dd1f60d1294fbf993749742bb9cfba40445/docs/docs/hardware-requirements/testnets.md#L8)
- Replace the `Along Goerli, it is one ....` with `It is one...` to avoid mentioning Goerli
- Eliminate Goerli from Tesnets set [here](https://github.com/NethermindEth/sedge/blob/b4ff9dd1f60d1294fbf993749742bb9cfba40445/docs/src/components/HomepageFeatures/index.js#L11)

2024-05-20 07:07 UTC, stdevMac approved these changes

2024-05-20 08:04 UTC, adriantpaez approved these changes

2024-05-20 08:05 UTC, merged