docs: Include lido-status command
NethermindEth/sedge pull request #403
Opened 2024-08-16 15:22 UTC by khalifaa55

## Changes:
-
## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Other (please describe): 

## Testing
**Requires testing**

- [ ] Yes
- [ ] No

**In case you checked yes, did you write tests?**

- [ ] Yes
- [ ] No

2024-08-20 12:20 UTC, AntiD2ta requested changes
Made a first review. This PR should change with #402 but looks mostly correct.

2024-08-20 12:20 UTC, AntiD2ta commented on docs/docs/quickstart/lido.mdx
> +### Additional Management Tasks
```suggestion
- Bond and rewards details

### Additional Management Tasks
```

2024-08-20 12:20 UTC, AntiD2ta commented on docs/docs/quickstart/lido.mdx
> +sedge lido-status <your_address>
```suggestion
sedge lido-status <your_reward_address>
```

2024-08-20 12:20 UTC, AntiD2ta commented on docs/docs/quickstart/lido.mdx
> +### Checking Node Operator Status
Please add more information regarding the reward address. It should be clear to the user what address to use as the command argument.

2024-08-21 09:42 UTC, khalifaa55 commented
@AntiD2ta changes addressed [here](https://github.com/NethermindEth/sedge/pull/403/commits/8d66c2cfef87fa833a45b824dfc3aeaa0726841d).

2024-08-22 11:41 UTC, AntiD2ta approved these changes

2024-09-12 14:00 UTC, merged