Integrate EL monitoring stack
NethermindEth/sedge pull request #406
Opened 2024-09-05 11:02 UTC by khalifaa55

## Changes:
- Integrate monitoring stack code from EL repo
## Types of changes

What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Other (please describe): 

## Testing
**Requires testing**

- [x] Yes
- [ ] No

**In case you checked yes, did you write tests?**

- [x] Yes
- [ ] No

2024-09-05 14:49 UTC, khalifaa55 commented
## Main Changes

- Merged [dockerManager](https://github.com/NethermindEth/eigenlayer/blob/d30b4350b21b0f143be5a6d06568c4b722003ec8/internal/docker/docker.go#L32) interface from EL repo with [serviceManager](https://github.com/NethermindEth/sedge/blob/7204e1379fa467eff03c79e0d9942dd5b4e264c2/internal/pkg/services/services.go#L52) interface from Sedge into [dockerServiceManager](https://github.com/NethermindEth/sedge/blob/b2640e59e606d267f3f28962a8f9e406e5649809/internal/pkg/services/docker.go#L48).

- Adjust code for [composeManager](https://github.com/NethermindEth/sedge/blob/b2640e59e606d267f3f28962a8f9e406e5649809/internal/monitoring/compose/compose.go#L37) from EL to use code from [CommandRunner](https://github.com/NethermindEth/sedge/blob/7204e1379fa467eff03c79e0d9942dd5b4e264c2/internal/pkg/commands/commands.go#L18) implementation. [composeManager in EL](https://github.com/NethermindEth/eigenlayer/blob/d30b4350b21b0f143be5a6d06568c4b722003ec8/internal/compose/compose.go#L27).

- Include `monitoring` package in internal/monitoring which has all packages needed by the `monitoringStack` from EL .

- Generate mocks needed by the new packages in internal/monitoring into `sedge_mocks` package, except for internal/monitoring/locker/lock.go mocks are generated in internal/monitoring/locker/mocks (to prevent import cycles).

- Adjust file handling in test cases (in `monitoring` package) using [PathMatcher](https://github.com/NethermindEth/sedge/blob/b2640e59e606d267f3f28962a8f9e406e5649809/internal/monitoring/utils/pathMatcher.go#L21) to work with Windows as well as Linux OS.

- Remove unneeded code from [internal/monitoring/data](https://github.com/NethermindEth/sedge/tree/b2640e59e606d267f3f28962a8f9e406e5649809/internal/monitoring/data) package ([package in EL repo](https://github.com/NethermindEth/eigenlayer/tree/d30b4350b21b0f143be5a6d06568c4b722003ec8/internal/data))

2024-09-16 11:10 UTC, AntiD2ta requested changes

2024-09-16 11:10 UTC, AntiD2ta commented on internal/monitoring/locker/lock.go
`monitoring` should define its interface for `Locker`, and we should have a separate package with the `FLock` implementation of Locker

2024-09-16 11:23 UTC, khalifaa55 commented on cli/monitoring.go
> +		log.Debugf("Monitoring stack status: unknown. Got error: %v", err)
It was in the EL code and I forgot to adjust it.

2024-09-16 14:54 UTC, khalifaa55 commented on internal/monitoring/compose/compose.go
I will log this refactoring task alongside [this task](https://github.com/NethermindEth/sedge/pull/406#discussion_r1760913258) to work on them together.

2024-09-16 15:18 UTC, khalifaa55 commented on CHANGELOG.md
> +- Monitoring setup for Lido CSM Node.
[Done](https://github.com/NethermindEth/sedge/pull/406/commits/c2c68290b30c4ae14f4558e099cdc975012023a0)

2024-09-16 15:19 UTC, khalifaa55 commented on go.mod
> +go 1.22
[Done](https://github.com/NethermindEth/sedge/pull/406/commits/c2c68290b30c4ae14f4558e099cdc975012023a0)

2024-09-16 15:20 UTC, khalifaa55 commented on internal/monitoring/services/grafana/service_test.go
> +	locker.EXPECT().New(utils.PathMatcher{Expected: filepath.Join(basePath, "/monitoring", ".lock")}).Return(locker)
[Done](https://github.com/NethermindEth/sedge/pull/406/commits/4bf68211784d25f600b0c5223696cb291a668a56). (It works!)

2024-09-16 15:20 UTC, khalifaa55 commented on cli/monitoringManager.go
> +	// The dockerNetwork is the name of the network the node is connected to.
[Done](https://github.com/NethermindEth/sedge/pull/406/commits/4bf68211784d25f600b0c5223696cb291a668a56)

2024-09-16 15:21 UTC, khalifaa55 commented on cli/monitoringManager.go
> +	// Cleanup removes the monitoring stack. If force is true, it will remove the stack directly bypassing any checks.
[Done](https://github.com/NethermindEth/sedge/pull/406/commits/4bf68211784d25f600b0c5223696cb291a668a56)

2024-09-16 15:21 UTC, khalifaa55 commented on cli/monitoring.go
> +		log.Debugf("Monitoring stack status: unknown. Got error: %v", err)
[Done](https://github.com/NethermindEth/sedge/pull/406/commits/4bf68211784d25f600b0c5223696cb291a668a56)

2024-09-16 15:21 UTC, khalifaa55 commented on cli/monitoring_test.go
> +func TestMonitoringCmd(t *testing.T) {
[Done](https://github.com/NethermindEth/sedge/pull/406/commits/4bf68211784d25f600b0c5223696cb291a668a56)

2024-09-16 15:22 UTC, khalifaa55 commented on internal/monitoring/locker/lock.go
[Done](https://github.com/NethermindEth/sedge/pull/406/commits/f147b8b079a2425af8eb33fdae877b4019bec7e3)

2024-09-17 06:09 UTC, AntiD2ta requested changes

2024-09-17 06:09 UTC, AntiD2ta commented on internal/monitoring/services/prometheus/dotenv.go
> +	"PROM_IMAGE": "prom/prometheus:v2.54.0",
```suggestion
	"PROM_IMAGE": "prom/prometheus:v2.54.1",
```

2024-09-17 06:09 UTC, AntiD2ta commented on internal/monitoring/services/prometheus/error.go
> +	ErrInvalidOptions = errors.New("invalid options for grafana setup")
Grafana or Prometheus?

2024-09-17 08:37 UTC, khalifaa55 commented on internal/monitoring/data/testdata/option-returner/.env
[Done](https://github.com/NethermindEth/sedge/pull/406/commits/c03d51c5a6a27d2a86b37567da145345faf15f52)

2024-09-17 08:37 UTC, khalifaa55 commented on internal/monitoring/services/grafana/dashboards/common-metrics/common-metrics-global.json
[Done](https://github.com/NethermindEth/sedge/pull/406/commits/c03d51c5a6a27d2a86b37567da145345faf15f52)

2024-09-17 08:39 UTC, khalifaa55 commented on internal/monitoring/services/prometheus/error.go
> +	ErrInvalidOptions = errors.New("invalid options for grafana setup")
[Done](https://github.com/NethermindEth/sedge/pull/406/commits/ba8f2b66754552ab9511c6fafcdcb0a765da5b3e)

2024-09-17 08:39 UTC, khalifaa55 commented on internal/monitoring/services/prometheus/dotenv.go
> +	"PROM_IMAGE": "prom/prometheus:v2.54.0",
[Done](https://github.com/NethermindEth/sedge/pull/406/commits/ba8f2b66754552ab9511c6fafcdcb0a765da5b3e)

2024-09-17 08:39 UTC, khalifaa55 commented on internal/monitoring/services/node_exporter/dotenv.go
> +	"NODE_EXPORTER_IMAGE": "prom/node-exporter:v1.7.0",
[Done](https://github.com/NethermindEth/sedge/pull/406/commits/ba8f2b66754552ab9511c6fafcdcb0a765da5b3e)

2024-09-17 08:39 UTC, khalifaa55 commented on internal/monitoring/services/grafana/dotenv.go
> +	"GRAFANA_IMAGE":          "grafana/grafana-oss:11.0.4",
[Done](https://github.com/NethermindEth/sedge/pull/406/commits/ba8f2b66754552ab9511c6fafcdcb0a765da5b3e)

2024-09-17 08:39 UTC, khalifaa55 commented on internal/monitoring/locker/lock.go
> +type Locker interface {
[Done](https://github.com/NethermindEth/sedge/pull/406/commits/ba8f2b66754552ab9511c6fafcdcb0a765da5b3e)

2024-09-17 08:57 UTC, khalifaa55 commented on internal/monitoring/services/grafana/dashboards/common-metrics/common-metrics-global.json
Update: I will need to keep them for now because the tests depend on the existence of these files. Once we add the new ones we could remove those.

2024-09-17 09:03 UTC, khalifaa55 commented on internal/monitoring/data/datadir.go
Done

2024-09-17 09:13 UTC, AntiD2ta approved these changes
Approved! Terrific job @khalifaa55 !

2024-09-17 09:25 UTC, merged