Add OP stack using nethermind to Sedge
NethermindEth/sedge pull request #407
Opened 2024-09-05 13:43 UTC by stdevMac

## Changes:
- Add op stack to Sedge using nethermind
- Support on Mainnet and Sepolis

## Types of changes
- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Testing
**Requires testing**

- [x] Yes
- [ ] No

**In case you checked yes, did you write tests?**

- [x] Yes
- [ ] No

**Comments about testing , should you have some** (optional)
We have been testing manually this setup on the core team for the last few months, some extra tests needs to be integrated later

2024-09-05 13:56 UTC, cbermudez97 approved these changes

2024-09-05 19:13 UTC, AntiD2ta requested changes
Please keep the flag `--consensus-url` and don't rename it as this is a breaking change.

I have concerns regarding the `--op-enabled` flag and if it is required (there is also no mention on it on the OP doc setup page u added)

2024-09-05 19:13 UTC, AntiD2ta commented on docs/docs/quickstart/optimism.mdx
There is no mention on how the full node setup lool like (what services) and that we are using Nethermind for the L2 execution client

2024-09-06 09:10 UTC, stdevMac commented on docs/docs/quickstart/optimism.mdx
Added more context and tips here [bd0819c](https://github.com/NethermindEth/sedge/pull/407/commits/bd0819cd9319e450d9d184f61cd4b8488f0867ab)

2024-09-06 09:10 UTC, stdevMac commented on configs/client_images.yaml
Added it here [01e0412](https://github.com/NethermindEth/sedge/pull/407/commits/01e0412d8c4ea3ff0e0f9e79e06a6ca8e0d37904)

2024-09-06 09:17 UTC, AntiD2ta commented on docs/docs/quickstart/optimism.mdx
> +This is useful in case you have already an endpoint for the execution node. It will safe synchronization time.
```suggestion
This is useful if you already have an endpoint for the execution node. It will save synchronization time.
```

2024-09-06 09:17 UTC, AntiD2ta approved these changes

2024-09-06 15:04 UTC, merged